/*
Package wd GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package wd

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (Dir) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (v OSInfo) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OSVersion":
			return []string{}, true
		case "Platform":
			return []string{}, true
		case "Home":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.OSVersion, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (OptionFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (v Options) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "BasePath":
			return []string{}, true
		case "Env":
			return []string{}, true
		case "User":
			return []string{}, true
		case "Stdout":
			return []string{}, true
		case "Stderr":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
