/*
Package flow GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package flow

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Every) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Steps":
			return []string{
				"do the step one by one",
			}, true
		case "Result":
			return []string{
				"util every step ok",
			}, true

		}
		if doc, ok := runtimeDoc(v.Group, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"Every task group",
	}, true
}

func (v EveryResult) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Ok":
			return []string{}, true
		case "Results":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v ResultInterface) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Ok":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"ResultInterface",
		"support additional fields but the `ok: bool`",
	}, true
}

func (v Some) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Steps":
			return []string{
				"do the step one by one",
			}, true
		case "Result":
			return []string{
				"util some step ok, and remain steps will not execute.",
			}, true

		}
		if doc, ok := runtimeDoc(v.Group, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"Some task group",
	}, true
}

func (v StepInterface) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Result":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"StepInterface",
		"support additional fields but must the `result: ResultInterface` as result checking",
	}, true
}
