/*
Package client GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package client

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Any) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Value":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Env) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Env":
			return []string{
				"pick the requested env vars",
			}, true

		}

		return nil, false
	}
	return []string{
		"Env of client",
	}, true
}

func (v Merge) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Inputs":
			return []string{}, true
		case "Output":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"Merge",
		"read secret value for the secret",
	}, true
}

func (v ReadSecret) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Secret":
			return []string{
				"secret ref",
			}, true
		case "Value":
			return []string{
				"secret value",
			}, true

		}

		return nil, false
	}
	return []string{
		"ReadSecret",
		"read secret value for the secret",
	}, true
}

func (v RevInfo) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "SetupTask":
			return []string{}, true
		case "Version":
			return []string{
				"get pseudo version same of go mod",
				"like",
				"v0.0.0-20231222030512-c093d5e89975",
				"v0.0.0-dirty.0.20231222022414-5f9d1d44dacc",
			}, true

		}
		if doc, ok := runtimeDoc(v.SetupTask, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Secret) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {

		}

		return nil, false
	}
	return []string{}, true
}

func (v SecretOrString) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Secret":
			return []string{}, true
		case "Value":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (StringOrBytes) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (StringOrSlice) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
