/*
Package engine GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package engine

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (LogLevel) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (v Logger) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "LogLevel":
			return []string{
				"Log level",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Pipeline) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Action":
			return []string{}, true
		case "Project":
			return []string{
				"plan root file",
				"and the dir of the root file will be the cwd for all cue files",
			}, true
		case "CacheDir":
			return []string{
				"cache dir root",
				"for cache files",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
