/*
Package cueify GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package cueify

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Decl) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "PkgPath":
			return []string{}, true
		case "Name":
			return []string{}, true
		case "Doc":
			return []string{}, true
		case "Source":
			return []string{}, true
		case "Imports":
			return []string{}, true
		case "Fields":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Field) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Doc":
			return []string{}, true
		case "Embed":
			return []string{}, true
		case "Idx":
			return []string{}, true
		case "Type":
			return []string{}, true
		case "AsOutput":
			return []string{}, true
		case "Optional":
			return []string{}, true
		case "Inline":
			return []string{}, true
		case "DefaultValue":
			return []string{}, true
		case "Enum":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (OptionFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
