/*
Package ociutil GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package ociutil

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v ManifestPatcher) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Annotations":
			return []string{}, true
		}

		return nil, false
	}
	return []string{}, true
}

func (v OciTarPatcher) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Manifests":
			return []string{}, true
		}

		return nil, false
	}
	return []string{}, true
}
