/*
Package list GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package list

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v List[V]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Front":
			return []string{}, true
		case "Back":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Node[V]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Value":
			return []string{}, true
		case "Prev":
			return []string{}, true
		case "Next":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
