name: release

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ ship, release, ship-distroless ]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.25.0'

      - run: just ${{ matrix.target }}
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

