/*
Package chunk GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package chunk

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Chunk) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Offset":
			return []string{}, true
		case "Size":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (FileSize) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (OptionFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
